# Run the CI for pre-commit
name: LINTING

on:
  # Triggers the workflow on push or pull request events for the master branch
  #  or by manually running from the Actions tab.
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: ["opened", "reopened", "synchronize", "ready_for_review"]
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linters:
    runs-on: ubuntu-latest
    # don't run CI on draft PRs
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    name: Linting (Python ${{ matrix.python-version }})

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install system dependencies (if needed)
        run: |
          sudo apt-get update

      - uses: pre-commit/action@v3.0.1
